<a href="https://colab.research.google.com/github/saimanhamal/ok/blob/main/Worksheet_0_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6CS012 Worksheet - 0: Python and NumPy for Deep Learning
**Student:** Saiman Hamal

---
## 4.1 Exercise on Functions

### Task 1: Unit Converter

In [1]:
def convert_length(value, direction):
    """
    Convert between meters and feet.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'm_to_ft' or 'ft_to_m'.

    Returns:
        float: Converted value.
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'm_to_ft' or 'ft_to_m'.")


def convert_weight(value, direction):
    """
    Convert between kilograms and pounds.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'kg_to_lbs' or 'lbs_to_kg'.

    Returns:
        float: Converted value.
    """
    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'kg_to_lbs' or 'lbs_to_kg'.")


def convert_volume(value, direction):
    """
    Convert between liters and gallons.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'l_to_gal' or 'gal_to_l'.

    Returns:
        float: Converted value.
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'l_to_gal' or 'gal_to_l'.")


def unit_converter():
    """
    Interactive unit converter for length, weight, and volume.
    Handles invalid input with try-except blocks.
    """
    print("Unit Converter")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = input("Choose conversion type (1/2/3): ").strip()
        value = float(input("Enter the value to convert: "))

        if choice == '1':
            direction = input("Direction? (m_to_ft / ft_to_m): ").strip()
            result = convert_length(value, direction)
            print(f"Result: {value} -> {result:.4f}")
        elif choice == '2':
            direction = input("Direction? (kg_to_lbs / lbs_to_kg): ").strip()
            result = convert_weight(value, direction)
            print(f"Result: {value} -> {result:.4f}")
        elif choice == '3':
            direction = input("Direction? (l_to_gal / gal_to_l): ").strip()
            result = convert_volume(value, direction)
            print(f"Result: {value} -> {result:.4f}")
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
    except ValueError as e:
        print(f"Error: {e}")


# --- Test without interactive input ---
print("=== Length: 10 meters to feet ===")
print(f"{convert_length(10, 'm_to_ft'):.4f} ft")

print("\n=== Weight: 70 kg to lbs ===")
print(f"{convert_weight(70, 'kg_to_lbs'):.4f} lbs")

print("\n=== Volume: 5 liters to gallons ===")
print(f"{convert_volume(5, 'l_to_gal'):.4f} gal")


=== Length: 10 meters to feet ===
32.8084 ft

=== Weight: 70 kg to lbs ===
154.3234 lbs

=== Volume: 5 liters to gallons ===
1.3209 gal


### Task 2: Mathematical Operations on a List

In [2]:
def compute_sum(numbers):
    """
    Compute the sum of a list of numbers.

    Parameters:
        numbers (list): List of numeric values.

    Returns:
        float: Sum of the list.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers)


def compute_average(numbers):
    """
    Compute the average of a list of numbers.

    Parameters:
        numbers (list): List of numeric values.

    Returns:
        float: Average of the list.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
        numbers (list): List of numeric values.

    Returns:
        float: Maximum value.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return max(numbers)


def compute_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
        numbers (list): List of numeric values.

    Returns:
        float: Minimum value.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return min(numbers)


def math_operations():
    """
    Interactive math operations on user-provided list of numbers.
    """
    print("Math Operations")
    print("1. Sum  2. Average  3. Maximum  4. Minimum")
    try:
        choice = input("Choose operation (1/2/3/4): ").strip()
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]

        ops = {'1': compute_sum, '2': compute_average,
               '3': compute_maximum, '4': compute_minimum}

        if choice in ops:
            result = ops[choice](numbers)
            print(f"Result: {result}")
        else:
            print("Invalid choice.")
    except ValueError as e:
        print(f"Error: {e}")


# --- Test without interactive input ---
nums = [4, 7, 2, 9, 1, 5]
print(f"Numbers: {nums}")
print(f"Sum:     {compute_sum(nums)}")
print(f"Average: {compute_average(nums):.2f}")
print(f"Maximum: {compute_maximum(nums)}")
print(f"Minimum: {compute_minimum(nums)}")


Numbers: [4, 7, 2, 9, 1, 5]
Sum:     28
Average: 4.67
Maximum: 9
Minimum: 1


---
## 4.2 Exercise on List Manipulation

In [3]:
def extract_every_other(lst):
    """Return every other element starting from the first."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Return sublist from start to end (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Reverse a list using slicing."""
    return lst[::-1]

def remove_first_last(lst):
    """Remove the first and last elements."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Return the first n elements."""
    return lst[:n]

def get_last_n(lst, n):
    """Return the last n elements."""
    return lst[-n:]

def reverse_skip(lst):
    """Return every second element starting from second-to-last, going backward."""
    return lst[-2::-2]


# --- Tests ---
sample = [1, 2, 3, 4, 5, 6]
print(f"Original:            {sample}")
print(f"Every other:         {extract_every_other(sample)}")
print(f"Sublist [2..4]:      {get_sublist(sample, 2, 4)}")
print(f"Reversed:            {reverse_list(sample)}")
print(f"Remove first/last:   {remove_first_last(sample)}")
print(f"First 3:             {get_first_n(sample, 3)}")
print(f"Last 2:              {get_last_n(sample, 2)}")
print(f"Reverse skip:        {reverse_skip(sample)}")


Original:            [1, 2, 3, 4, 5, 6]
Every other:         [1, 3, 5]
Sublist [2..4]:      [3, 4, 5]
Reversed:            [6, 5, 4, 3, 2, 1]
Remove first/last:   [2, 3, 4, 5]
First 3:             [1, 2, 3]
Last 2:              [5, 6]
Reverse skip:        [5, 3, 1]


---
## 4.3 Exercise on Nested List

In [4]:
def flatten(lst):
    """Flatten a one-level nested list."""
    return [item for sublist in lst for item in sublist]

def access_nested_element(lst, indices):
    """Access element at given nested indices."""
    result = lst
    for idx in indices:
        result = result[idx]
    return result

def sum_nested(lst):
    """Recursively sum all elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """Remove all occurrences of elem from nested list."""
    return [[x for x in sublist if x != elem] for sublist in lst]

def find_max(lst):
    """Find max in a nested list (any depth)."""
    def _flatten(l):
        for item in l:
            if isinstance(item, list):
                yield from _flatten(item)
            else:
                yield item
    return max(_flatten(lst))

def count_occurrences(lst, elem):
    """Count occurrences of elem in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    """Flatten a deeply nested list of any depth."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

def average_nested(lst):
    """Calculate average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


# --- Tests ---
print("1. Flatten:", flatten([[1, 2], [3, 4], [5]]))
print("2. Access nested element:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1, 2]))
print("3. Sum nested:", sum_nested([[1, 2], [3, [4, 5]], 6]))
print("4. Remove element:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("5. Find max:", find_max([[1, 2], [3, [4, 5]], 6]))
print("6. Count occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("7. Deep flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("8. Average nested:", average_nested([[1, 2], [3, 4], [5, 6]]))


1. Flatten: [1, 2, 3, 4, 5]
2. Access nested element: 6
3. Sum nested: 21
4. Remove element: [[1], [3], [4, 5]]
5. Find max: 6
6. Count occurrences: 3
7. Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average nested: 3.5


---
## 10.1 Basic Vector and Matrix Operations with NumPy

### Problem 1: Array Creation

In [5]:
import numpy as np

# 1. Empty 2x2 array
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2:\n", empty_2x2)

# 2. All-ones 4x2 array
ones_4x2 = np.ones((4, 2))
print("\n2. Ones 4x2:\n", ones_4x2)

# 3. Array filled with a fill value (e.g., 7)
filled = np.full((3, 3), 7)
print("\n3. Full with 7:\n", filled)

# 4. Zeros with same shape as existing array
existing = np.array([[1, 2], [3, 4], [5, 6]])
zeros_like = np.zeros_like(existing)
print("\n4. Zeros like existing:\n", zeros_like)

# 5. Ones with same shape as existing array
ones_like = np.ones_like(existing)
print("\n5. Ones like existing:\n", ones_like)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\n6. Array from list:", arr_from_list)


1. Empty 2x2:
 [[5.03819556e-315 0.00000000e+000]
 [4.94065646e-324 6.71263572e-310]]

2. Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like existing:
 [[0 0]
 [0 0]
 [0 0]]

5. Ones like existing:
 [[1 1]
 [1 1]
 [1 1]]

6. Array from list: [1 2 3 4]


### Problem 2: Array Manipulation

In [6]:
import numpy as np

# 1. Values from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. Values 10 to 49:\n", arr_10_49)

# 2. 3x3 matrix with values 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0 to 8):\n", matrix_3x3)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("\n3. Identity matrix:\n", identity)

# 4. Random array of size 30, find mean
rand_arr = np.random.random(30)
print(f"\n4. Random array (size 30) mean: {rand_arr.mean():.4f}")

# 5. 10x10 random array, find min and max
rand_10x10 = np.random.random((10, 10))
print(f"\n5. 10x10 random - Min: {rand_10x10.min():.4f}, Max: {rand_10x10.max():.4f}")

# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse array
arr_rev = np.array([1, 2, 0, 0, 4, 0])
print("\n7. Reversed array:", arr_rev[::-1])

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border array:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", checkerboard)


1. Values 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30) mean: 0.4301

5. 10x10 random - Min: 0.0130, Max: 0.9914

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem 3: Array Operations

In [7]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("x =\n", x)
print("y =\n", y)
print("v =", v, " w =", w)

print("\n1. x + y =\n", x + y)
print("\n2. x - y =\n", x - y)
print("\n3. x * 3 =\n", x * 3)
print("\n4. x squared =\n", np.square(x))
print("\n5a. v · w =", np.dot(v, w))
print("\n5b. x · v =", np.dot(x, v))
print("\n5c. x · y =\n", np.dot(x, y))

# 6. Concatenate x and y along rows (axis=0), v and w along column
concat_rows = np.vstack((x, y))
print("\n6a. x vstack y =\n", concat_rows)
concat_vw = np.concatenate((v, w))
print("\n6b. v concat w =", concat_vw)

# 7. Concatenate x and v - this raises an error
print("\n7. Trying to concatenate x and v...")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"   Error: {e}")
    print("   Reason: x has shape (2,2) and v has shape (2,) — dimension mismatch.")
    print("   Fix: Reshape v to (1,2) first => np.concatenate((x, v.reshape(1,2)), axis=0)")
    print("   Result:\n", np.concatenate((x, v.reshape(1,2)), axis=0))


x =
 [[1 2]
 [3 5]]
y =
 [[5 6]
 [7 8]]
v = [ 9 10]  w = [11 12]

1. x + y =
 [[ 6  8]
 [10 13]]

2. x - y =
 [[-4 -4]
 [-4 -3]]

3. x * 3 =
 [[ 3  6]
 [ 9 15]]

4. x squared =
 [[ 1  4]
 [ 9 25]]

5a. v · w = 219

5b. x · v = [29 77]

5c. x · y =
 [[19 22]
 [50 58]]

6a. x vstack y =
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b. v concat w = [ 9 10 11 12]

7. Trying to concatenate x and v...
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Reason: x has shape (2,2) and v has shape (2,) — dimension mismatch.
   Fix: Reshape v to (1,2) first => np.concatenate((x, v.reshape(1,2)), axis=0)
   Result:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


### Problem 4: Matrix Operations

In [8]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("A =\n", A)
print("B =\n", B)

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
product_AI = np.round(A @ A_inv, 6)
print("\n1. A · A⁻¹ =\n", product_AI, "  ✓ Identity")

# 2. Prove AB != BA
AB = A @ B
BA = B @ A
print("\n2. AB =\n", AB)
print("   BA =\n", BA)
print("   AB == BA?", np.allclose(AB, BA), "  ✓ Not equal")

# 3. Prove (AB)^T = B^T * A^T
ABT = (A @ B).T
BTAT = B.T @ A.T
print("\n3. (AB)ᵀ =\n", ABT)
print("   BᵀAᵀ =\n", BTAT)
print("   Equal?", np.allclose(ABT, BTAT), "  ✓ Proved")


A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]]

1. A · A⁻¹ =
 [[1. 0.]
 [0. 1.]]   ✓ Identity

2. AB =
 [[23 13]
 [51 29]]
   BA =
 [[36 44]
 [13 16]]
   AB == BA? False   ✓ Not equal

3. (AB)ᵀ =
 [[23 51]
 [13 29]]
   BᵀAᵀ =
 [[23 51]
 [13 29]]
   Equal? True   ✓ Proved


#### Solving System of Linear Equations

In [9]:
import numpy as np

# System:
# 2x - 3y +  z = -1
#  x -  y + 2z = -3
# 3x +  y -  z =  9

A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]], dtype=float)

B_sys = np.array([-1, -3, 9], dtype=float)

# Method 1: Manual inverse method
A_inv = np.linalg.inv(A_sys)
X_manual = A_inv @ B_sys
print("Inverse Method Solution:")
print(f"  x = {X_manual[0]:.4f}, y = {X_manual[1]:.4f}, z = {X_manual[2]:.4f}")

# Method 2: np.linalg.inv (same but explicit)
X_inv = np.linalg.inv(A_sys) @ B_sys
print("\nnp.linalg.inv Solution:")
print(f"  x = {X_inv[0]:.4f}, y = {X_inv[1]:.4f}, z = {X_inv[2]:.4f}")

# Verify
print("\nVerification A @ X =", np.round(A_sys @ X_manual, 4), " == B =", B_sys)


Inverse Method Solution:
  x = 2.0000, y = 1.0000, z = -2.0000

np.linalg.inv Solution:
  x = 2.0000, y = 1.0000, z = -2.0000

Verification A @ X = [-1. -3.  9.]  == B = [-1. -3.  9.]


---
## 10.2 Experiment: How Fast is NumPy?

In [10]:
import numpy as np
import time

SIZE = 1_000_000

a_list = list(np.random.rand(SIZE))
b_list = list(np.random.rand(SIZE))
a_np   = np.array(a_list)
b_np   = np.array(b_list)

# --- 1. Element-wise Addition ---
t0 = time.time()
result_loop = [a_list[i] + b_list[i] for i in range(SIZE)]
t1 = time.time()
loop_add = t1 - t0

t0 = time.time()
result_np = a_np + b_np
t1 = time.time()
np_add = t1 - t0

print(f"1. Addition - List: {loop_add:.5f}s | NumPy: {np_add:.5f}s | Speedup: {loop_add/np_add:.1f}x")

# --- 2. Element-wise Multiplication ---
t0 = time.time()
result_loop = [a_list[i] * b_list[i] for i in range(SIZE)]
t1 = time.time()
loop_mul = t1 - t0

t0 = time.time()
result_np = a_np * b_np
t1 = time.time()
np_mul = t1 - t0

print(f"2. Multiply - List: {loop_mul:.5f}s | NumPy: {np_mul:.5f}s | Speedup: {loop_mul/np_mul:.1f}x")

# --- 3. Dot Product ---
t0 = time.time()
dot_loop = sum(a_list[i] * b_list[i] for i in range(SIZE))
t1 = time.time()
loop_dot = t1 - t0

t0 = time.time()
dot_np = np.dot(a_np, b_np)
t1 = time.time()
np_dot_time = t1 - t0

print(f"3. Dot Prod - List: {loop_dot:.5f}s | NumPy: {np_dot_time:.5f}s | Speedup: {loop_dot/np_dot_time:.1f}x")

# --- 4. Matrix Multiplication (1000x1000) ---
M = 1000
A_mat = [[np.random.rand() for _ in range(M)] for _ in range(M)]
B_mat = [[np.random.rand() for _ in range(M)] for _ in range(M)]
A_np  = np.random.rand(M, M)
B_np  = np.random.rand(M, M)

t0 = time.time()
# Pure Python matrix multiplication (truncated for time)
C = [[sum(A_mat[i][k]*B_mat[k][j] for k in range(M)) for j in range(M)] for i in range(M)]
t1 = time.time()
loop_mm = t1 - t0

t0 = time.time()
C_np = A_np @ B_np
t1 = time.time()
np_mm = t1 - t0

print(f"4. MatMul  - List: {loop_mm:.5f}s | NumPy: {np_mm:.5f}s | Speedup: {loop_mm/np_mm:.1f}x")


1. Addition - List: 0.16959s | NumPy: 0.00234s | Speedup: 72.5x
2. Multiply - List: 0.15442s | NumPy: 0.00401s | Speedup: 38.5x
3. Dot Prod - List: 0.18973s | NumPy: 0.00144s | Speedup: 131.6x
4. MatMul  - List: 192.39842s | NumPy: 0.05910s | Speedup: 3255.3x
